name: github pages draft

on:
  push:
    branches:
    - draft

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v3
        fetch-depth: 0
      # with:
      #   submodules: true

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.110.0'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.TP }}        
        publish_branch: gh-pages
        publish_dir: ./public
        user_name: 'AP-actions[bot]'
        user_email: 'ap@biger.cc'
