name: github pages draft

on:
  push:
    branches:
    - draft

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # with:
      #   submodules: true

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.78.2'
        extended: true

    - name: Build
      run: hugo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.TP }}        
        publish_branch: gh-pages
        publish_dir: ./public
        user_name: 'AP-TiDB-actions[bot]'
        user_email: 'ap@tidb.cc'
