name: github pages

on:
  push:
    branches:
    - draft

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      # with:
      #   submodules: true

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.78.2'
        extended: true

    - name: Build
      run: hugo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TP }}        
        publish_branch: gh-pages
        publish_dir: ./public
        user_name: 'TiDB-AP-actions[bot]'
        user_email: 'ap.tidb.cc'
        commit_message: ${{ github.event.head_commit.message }}
